"""переход на JSON фильтры

Revision ID: 98987cf53b05
Revises: af35787d8acc
Create Date: 2026-06-10 19:50:23.146214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '98987cf53b05'
down_revision: Union[str, Sequence[str], None] = 'af35787d8acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters_hh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_hh_tg_id'), 'filters_hh', ['tg_id'], unique=True)
    op.drop_index(op.f('ix_filters_city'), table_name='filters')
    op.drop_index(op.f('ix_filters_salary'), table_name='filters')
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_table('filters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('salary_from', sa.INTEGER(), nullable=False),
    sa.Column('salary_to', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), server_default=sa.text("'any'"), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payday', sa.VARCHAR(length=100), nullable=True),
    sa.Column('experience', sa.INTEGER(), nullable=True),
    sa.Column('employmentZan', sa.VARCHAR(length=100), nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=100), nullable=True),
    sa.Column('work_hours', sa.INTEGER(), nullable=True),
    sa.Column('work_format', sa.VARCHAR(length=100), nullable=True),
    sa.Column('newest_first', sa.BOOLEAN(), nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('find_key_words', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('exclude_key_words', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=1)
    op.create_index(op.f('ix_filters_salary'), 'filters', ['salary_from', 'salary_to'], unique=False)
    op.create_index(op.f('ix_filters_city'), 'filters', ['city'], unique=False)
    op.drop_index(op.f('ix_filters_hh_tg_id'), table_name='filters_hh')
    op.drop_table('filters_hh')
    # ### end Alembic commands ###
