"""добавлена таблица вакансий

Revision ID: a61e4168aa5c
Revises: 98987cf53b05
Create Date: 2026-07-08 01:39:38.184501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61e4168aa5c'
down_revision: Union[str, Sequence[str], None] = '98987cf53b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'SKIP', name='actiontype'), nullable=False),
    sa.Column('vacancy_title', sa.String(length=255), nullable=True),
    sa.Column('vacancy_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_user_vacancy_action')
    )
    op.create_index(op.f('ix_vacancy_actions_user_id'), 'vacancy_actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_vacancy_actions_vacancy_id'), 'vacancy_actions', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_actions_vacancy_id'), table_name='vacancy_actions')
    op.drop_index(op.f('ix_vacancy_actions_user_id'), table_name='vacancy_actions')
    op.drop_table('vacancy_actions')
    # ### end Alembic commands ###
