"""initial_migration

Revision ID: af35787d8acc
Revises: 
Create Date: 2026-06-10 18:21:16.997768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af35787d8acc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_seen_in_bot', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=False),
    sa.Column('salary_to', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), server_default='any', nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('payday', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('employmentZan', sa.String(length=100), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('work_hours', sa.Integer(), nullable=True),
    sa.Column('work_format', sa.String(length=100), nullable=True),
    sa.Column('newest_first', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('find_key_words', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('exclude_key_words', sa.JSON(), server_default='[]', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filters_city', 'filters', ['city'], unique=False)
    op.create_index('ix_filters_salary', 'filters', ['salary_from', 'salary_to'], unique=False)
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_index('ix_filters_salary', table_name='filters')
    op.drop_index('ix_filters_city', table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
